### ISSUE TITLE
No Graylog2 servers available. Cannot log in.  

### ISSUE THREAD

**Issue by ychoucha** [mrlesmithjr/graylog2#17]
hello after installation.

i reboot my server
and when i restart i have the error : 
 and i don't know how lunch graylog2, so i p uppgrade 

how fix that please ?
![erreur_graylog2](https://cloud.githubusercontent.com/assets/301074/2564467/d61c94e4-b8a0-11e3-9384-867ebe213377.png)

**Comment by blackstar257** [comment]
I am having the same issue. Just randomly after the upgrade to the latest version. Im now unable to login.
