### ISSUE TITLE
Graylog2 Web Interface is disconnected.

### ISSUE THREAD

**Issue by Ramasudhastv** [mrlesmithjr/graylog2#23]
I have installed elastic search elasticsearch-0.20.6 , mongodb , graylog2-server-0.12.0 and graylog2-web-interface-0.20.3   .java version "1.7.0_51"

When am trying to access Graylog2 interface am getting the below error

No Graylog2 servers available. Cannot log in

"The web interface was unable to connect to any Graylog2 node in the cluster so far.
Please check that the configured nodes shown on the left hand side are correct and that the servers are reachable. "

**Comment by nrdate** [comment]
I am facing same issue but my OS for graylog is ubuntu.
I am not able to see server list under source tab..

**Comment by sinisterrook** [comment]
Would appreciate if this wasn't closed.  This isn't an isolated issue and the documentation doesn't have a very good troubleshooting section.  I'm on ubuntu as well and I'm having the same issues

**Comment by mrlesmithjr** [comment]
I will be glad to leave this open if anyone else is interested in taking over on this. I am no longer doing any development on this and all of my efforts are now focused on Ansible installations.

**Comment by mrlesmithjr** [comment]
https://github.com/mrlesmithjr/ansible-graylog
