### ISSUE TITLE
connect to localhost port 12900 (tcp) failed: Connection refused

### ISSUE THREAD

**Issue by jas0nkim** [mrlesmithjr/graylog2#30]
I have tried to install graylog2 into my ubuntu 12.04 instance from Linode with running install_graylog2_90_ubuntu.sh script. And having the issue:

connect to localhost port 12900 (tcp) failed: Connection refused

and unable to complete the installation.
Any help will be appreciated.

**Comment by mrlesmithjr** [comment]
This has been resolved in the script.
