### ISSUE TITLE
Missing binary 'nc'

### ISSUE THREAD

**Issue by h4cc** [mrlesmithjr/graylog2#35]
The binary for netcat is missing on my system:
> ./graylog2/install_graylog2_90_ubuntu.sh: line 84: nc: command not found

Please add somewhere `apt-get -y install netcat`.

**Comment by zstarer** [comment]
I put together a script for 0.92.3 and built it in case this happened for anyone else.
You won't be able to do an in-place upgrade, but it's there for the future (line 43).
https://github.com/zstarer/graylog2

release notes:
https://www.graylog2.org/news/post/0013-graylog2-v0-92-3
