### ISSUE TITLE
nc: connect to localhost port 12900 (tcp) failed: Connection refused problem

### ISSUE THREAD

**Issue by chrispcall** [mrlesmithjr/graylog2#37]
First off, thanks for writing this script!

I'm on a fresh install of Ubuntu 14.04 and trying to install via your script and at the very end, the message "nc: connect to localhost port 12900 (tcp) failed: Connection refused" begins to appear and continues repeating.  

Any ideas what this could be?

Thanks again,
Chris

**Comment by zstarer** [comment]
12900 is the port the graylog web server uses. I think I've seen that before, but it's not really an issue as there's a previous check in the script to make sure the webserver is up and responding.

did you have a problem accessing the web interface?
