### ISSUE TITLE
No Graylog servers available. Cannot log in.

### ISSUE THREAD

**Issue by saurabhksingh** [mrlesmithjr/graylog2#39]
I used AMI ami-75c9641e and followed the steps given on http://docs.graylog.org/en/latest/pages/installation/aws.html.
However I keep getting the error and this application is not useful to me.

**Comment by mrlesmithjr** [comment]
I would recommend trying out the Ansible based installs that I have created. I have not been investing time into this repo any longer. So check out the repo below.
https://github.com/mrlesmithjr/ansible-graylog
