### ISSUE TITLE
graylog interface not showing up

### ISSUE THREAD

**Issue by yoramdag** [mrlesmithjr/graylog2#40]
Hi,

I a new to Graylog and trying to learn it.
I have installed the Appliances version with the instruction given in the web site.

I have deployed the appliances in VM-Ware work station for my tests.
8GB Ram
20GB HD
2 CPU

When accessing the web interface I get connection refused error from the browser.
Are there any settings to be done in the VM?
Where can I find some logs to help be troubleshoot the issue.

Thanks for the help
Y

**Comment by mrlesmithjr** [comment]
@yoramdag - I have not put any additional development into that appliance in some time so I am fairly positive there are issues with it. I have been actively developing the latest versions of Graylog to be deployed with Ansible. You can check out the repo for this at the following link if you are interested. I will keep this issue open for now though in case someone else happens to have some info on this that they would like to share. Hope this helps!
https://github.com/mrlesmithjr/ansible-graylog
