### ISSUE TITLE
default sshd keys exist in OVA image of appliance

### ISSUE THREAD

**Issue by te6** [mrlesmithjr/graylog2#44]
Please add a step to your OVA (and maybe other) creation procedure to remove the host keys prior to creating the image.  sshd should create new host keys on first boot.
As it stands, every server starts with the same host keys.

This was seen using the following image: graylog-beta-2.0.0-alpha.5-1.ova

**Comment by mrlesmithjr** [comment]
@te6 - Wow...people are still using this? I have not done anything with that OVA in years :)

**Comment by te6** [comment]
Oh... Well, its the only one I've been able to get to run...and then, only once...

________________________________________

**Comment by mrlesmithjr** [comment]
Have you pinged the guys at Graylog? Lennart possibly? Not sure what they
are doing with the development of Graylog OVA's.

On Thu, Apr 28, 2016 at 4:09 PM, te6 <notifications@github.com> wrote:

> Oh... Well, its the only one I've been able to get to run...and then, only
> once...
>
> ________________________________________
> From: Larry Smith Jr. [notifications@github.com]
> Sent: 28 April 2016 15:48
> To: mrlesmithjr/graylog2
> Cc: Theodore Van Iderstine; Mention
> Subject: Re: [mrlesmithjr/graylog2] default sshd keys exist in OVA image
> of appliance (#44)
>
> @te6<https://github.com/te6> - Wow...people are still using this? I have
> not done anything with that OVA in years :)
>
> �
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub<
> https://github.com/mrlesmithjr/graylog2/issues/44#issuecomment-215541482>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrlesmithjr/graylog2/issues/44#issuecomment-215547155>
>



-- 
Twitter @mrlesmithjr <http://twitter.com/mrlesmithjr>
Blog EverythingShouldBeVirtual.com
Interested in blog sponsorship? Go to http://bit.ly/10Aj7Sq

**Comment by te6** [comment]
No, its not that important to me...
I'll try installing from rpm/source on a VM again.  I just pulled the OVA because that was the strictly simplest option.

I did wonder why it was running Ubuntu 14.04...

thanks.

________________________________________
