### ISSUE TITLE
where are the RPMs for installations not from the internet

### ISSUE THREAD

**Issue by Bern9876** [mrlesmithjr/graylog2#45]
All i can find is the yum repository downloads which then reach out to get the other software or I can download source code. Where are the linux noarch RPMs ? please create the ones we need for graylog server and web interface for at least version 2.2 or 2.1.2 for us.

**Comment by mrlesmithjr** [comment]
@Bern9876 - I am no longer maintaining this repo as of about 2-3 years now. All development of Graylog provisioning is now done via [Ansible] and you can find that repo [here]. But please feel free to fork this repo and submit any PR's you deem necessary and I will review and merge them.

[Ansible]: <https://www.ansible.com>
[here]: <https://github.com/mrlesmithjr/ansible-graylog>
